pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
  
name: Siwei He
url: http://siweiho.github.com
github: SiweiHo
description: Welcome to Siwei's Hompage
gravatar_url: /apple-touch-icon.png

