markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Siwei He
url: http://siweiho.github.com
description: A fantastic blog that is fantastic.
github: SiweiHo

